# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main


pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'production'
  system.debug: 'true'

steps:
- script: |
    cd FE/SEP490/
    npm install
    npm run build-prod
  displayName: 'Build angular app'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/FE/SEP490/dist'
    ArtifactName: 'angular-app'
  displayName: 'Publist Build Artifacts'
